export const USERLOADING = "USERLOADING";
export const USERSUCCESS = "USERSUCCESS";
export const USERERROR = "USERERROR";

export const GETDATALOADING = "GETDATALOADING";
export const GETDATASUCCESS = "GETDATASUCCESS";
export const GETDATAERROR = "GETDATAERROR";
export const GETSUGGESTIONSSUCCESS = "GETSUGGESTIONSSUCCESS";
